### ISSUE TITLE
Final form example errors on the latest version of Fulcro

### ISSUE THREAD

**Issue by yayitswei** [fulcrologic/video-series#1]
Hi, first of all, thanks for making Fulcro and putting out high quality documentation. I'm learning Fulcro from scratch and finding the documentation helpful. This repo was linked from the Fulcro 3 tutorial videos, so I consider it a definitive source, and I'd like for it to work in 3.0.9 so I can base my own work off the most recent version.

Repro: https://github.com/yayitswei/video-series/tree/form-bug-repro
My branch has the following changes from the `form-final` branch of this repo:
- Update fulcro version from `3.0.1` to `3.0.9`
- Update pathom version from `2.2.24` to `2.2.26`
- Add a ghostwheel dep
- Update `mark-complete` to account for new behavior

Run the app. Edit an item, then attempt to save it and note the exception in the console:
```
ERROR [com.fulcrologic.fulcro.algorithms.form-state:506] - FORM NOT NORMALIZED: [:item/id 1]
```

What are the steps for migrating the form tutorial to fulcro 3.0.9? Thanks!

**Comment by awkay** [comment]
Thanks for the report. There should be no changes between the two, but I may have made a mistake when making the video.  I don't have a ton of time to review things right now. When you say "update mark-complete" to account for new behavior what do you mean...there should be no new behavior in form state support.  The only thing that has changed in form state over time is bug fixes.

**Comment by yayitswei** [comment]
Thanks, good to know that there's only bugfixes in the form state.

Re: update mark-complete, I changed this line: https://github.com/yayitswei/video-series/commit/31dc0be0a61eae9f500f8509f5a83e18c7a755ce#diff-f489ca8ea272cccece0cee7428cd1ac0L78.

`mark-complete` without any attributes seems to have no effect here, so I had to add the editable item attributes so it the item would validate.

**Comment by yayitswei** [comment]
FWIW I did a bisect and found that the problem happens between `3.0.1` (good) and `3.0.2` (bad).

**Comment by awkay** [comment]
Hm...nothing at all changes WRT form-state there.

Your code is incorrect.  `mark-complete*` *either* takes no fields (and marks them all) or takes a *single* field (keyword).  Giving it a vector is not supported.

**Comment by yayitswei** [comment]
Thanks for looking into this, I've reverted the change on my end. Forgive my hand-wavy approach to debugging here but I'm still learning how everything works.

Without changing your original tutorial code, a changed item is still marked invalid in `3.0.9` but it's marked valid in the latest version, `3.1.5-RC1`. Works for me so I'm closing the issue.
